


import { ReviewLayer, LayerAnalysisData, ReviewStage, TokenBudgetConfig, MonthlyScoreboardItem } from './types';
import { BookOpenIcon } from './components/icons/BookOpenIcon';
import { CameraIcon } from './components/icons/CameraIcon';
import { UsersIcon } from './components/icons/UsersIcon';

export const GEMINI_MODEL_TEXT = 'gemini-1.5-flash-latest';
export const MAX_SCORE = 10; // Define a maximum score for layers

export const LAYER_DEFINITIONS: Omit<LayerAnalysisData, 'aiGeneratedText' | 'editedText' | 'isLoading' | 'error' | 'userScore' | 'groundingSources' | 'aiSuggestedScore' | 'improvementSuggestions' | 'vonnegutShape'>[] = [
  {
    id: ReviewLayer.STORY,
    title: 'Magic of Story/Script',
    shortTitle: 'Story',
    description: 'Core idea, narrative, themes, character arcs, originality.',
    icon: BookOpenIcon,
  },
  {
    id: ReviewLayer.CONCEPTUALIZATION,
    title: 'Magic of Conceptualization',
    shortTitle: 'Concept',
    description: "Director's vision, editing, casting, overall presentation.",
    icon: CameraIcon,
  },
  {
    id: ReviewLayer.PERFORMANCE,
    title: 'Magic of Performance/Execution',
    shortTitle: 'Performance',
    description: 'Acting, music, cinematography, effects, choreography.',
    icon: UsersIcon,
  },
];

export const initialLayerAnalyses = (): LayerAnalysisData[] =>
  LAYER_DEFINITIONS.map(def => ({
    ...def,
    aiGeneratedText: '',
    editedText: '',
    isLoading: false,
    error: null,
    aiSuggestedScore: undefined, 
    userScore: undefined, 
    groundingSources: [], 
    improvementSuggestions: undefined,
    vonnegutShape: undefined, 
  }));

export const REVIEW_STAGES_OPTIONS: { value: ReviewStage; label: string }[] = [
  { value: ReviewStage.IDEA_ANNOUNCEMENT, label: 'Idea Announcement' },
  { value: ReviewStage.TRAILER, label: 'Trailer Analysis' },
  { value: ReviewStage.MOVIE_RELEASED, label: 'Full Movie/Series Review' },
];

export const LAYER_SHORT_NAMES: Record<ReviewLayer, string> = {
  [ReviewLayer.STORY]: 'Story',
  [ReviewLayer.CONCEPTUALIZATION]: 'Concept',
  [ReviewLayer.PERFORMANCE]: 'Performance',
};

export const COMMON_GENRES: string[] = [
  'Action',
  'Adventure',
  'Animation',
  'Biography',
  'Comedy',
  'Crime',
  'Documentary',
  'Drama',
  'Family',
  'Fantasy',
  'Film Noir',
  'Historical',
  'Horror',
  'Musical',
  'Mystery',
  'Romance',
  'Sci-Fi',
  'Sport',
  'Superhero',
  'Thriller',
  'War',
  'Western',
];

export const INITIAL_TOKEN_BUDGET_CONFIG: TokenBudgetConfig = {
  isEnabled: false,
  freeTierQueriesPerDay: undefined, 
  freeTierQueriesPerMinute: undefined, 
  lastDailyResetTimestamp: Date.now(),
};

export const CHARS_PER_TOKEN_ESTIMATE = 4;
export const MAX_TOKEN_LOG_ENTRIES = 50; 

export const MAGIC_QUOTIENT_DISCLAIMER = "This analysis is AI-generated and highly subjective. It aims to provide creative feedback and identify potential areas of strength or development based on common storytelling principles. It is not a predictor of actual market success or failure, as real-world outcomes are influenced by countless factors including execution, marketing, and audience reception. Use these insights as a tool for further thought and refinement.";

export const MOCK_MONTHLY_SCOREBOARD_DATA: MonthlyScoreboardItem[] = [
  // Recent Indian Cinema & OTT Releases (2024-2025)
  {
    id: 'msi001',
    title: 'Pushpa 2: The Rule',
    type: 'Movie',
    platform: 'Theatrical',
    releaseMonth: 'December 2024',
    greybrainerScore: 9.6,
    posterUrl: 'https://via.placeholder.com/150x220/8B4513/FFFFFF?text=Pushpa+2',
    summary: 'Allu Arjun returns as Pushpa Raj in this highly anticipated sequel that breaks box office records.',
    country: 'India',
    region: 'Andhra Pradesh',
    language: 'Telugu',
  },
  {
    id: 'msi002',
    title: 'Kalki 2898 AD',
    type: 'Movie',
    platform: 'Theatrical',
    releaseMonth: 'June 2024',
    greybrainerScore: 9.5,
    posterUrl: 'https://via.placeholder.com/150x220/4B0082/FFFFFF?text=Kalki+2898',
    summary: 'Prabhas stars in this futuristic sci-fi epic blending mythology with cutting-edge VFX.',
    country: 'India',
    region: 'Andhra Pradesh',
    language: 'Telugu',
  },
  {
    id: 'msi003',
    title: 'Manjummel Boys',
    type: 'Movie',
    platform: 'Disney+ Hotstar',
    releaseMonth: 'February 2024',
    greybrainerScore: 9.4,
    posterUrl: 'https://via.placeholder.com/150x220/228B22/FFFFFF?text=Manjummel+Boys',
    summary: 'A survival thriller based on the true story of friends trapped in Guna Caves, Kerala.',
    country: 'India',
    region: 'Kerala',
    language: 'Malayalam',
  },
  {
    id: 'msi004',
    title: 'Mirzapur: Season 3',
    type: 'Web Series',
    platform: 'Amazon Prime Video',
    releaseMonth: 'July 2024',
    greybrainerScore: 9.2,
    posterUrl: 'https://via.placeholder.com/150x220/8B0000/FFFFFF?text=Mirzapur+S3',
    summary: 'The brutal saga of power and crime continues in the lawless heartland of Uttar Pradesh.',
    country: 'India',
    region: 'Uttar Pradesh',
    language: 'Hindi',
  },
  {
    id: 'msi005',
    title: 'Stree 2: Sarkate Ka Aatank',
    type: 'Movie',
    platform: 'Theatrical',
    releaseMonth: 'August 2024',
    greybrainerScore: 9.1,
    posterUrl: 'https://via.placeholder.com/150x220/FF4500/FFFFFF?text=Stree+2',
    summary: 'Rajkummar Rao and Shraddha Kapoor return in this horror-comedy sequel that dominated the box office.',
    country: 'India',
    region: 'Maharashtra',
    language: 'Hindi',
  },
  {
    id: 'msi006',
    title: 'Scam 2003: The Telgi Story',
    type: 'Web Series',
    platform: 'Sony LIV',
    releaseMonth: 'September 2023',
    greybrainerScore: 9.0,
    posterUrl: 'https://via.placeholder.com/150x220/2F4F4F/FFFFFF?text=Scam+2003',
    summary: 'Gagan Dev Riar stars in this gripping tale of the stamp paper scam that shook India.',
    country: 'India',
    region: 'Karnataka',
    language: 'Hindi',
  },
  {
    id: 'msi007',
    title: 'Maharaja',
    type: 'Movie',
    platform: 'Netflix',
    releaseMonth: 'June 2024',
    greybrainerScore: 8.9,
    posterUrl: 'https://via.placeholder.com/150x220/8B4513/FFFFFF?text=Maharaja',
    summary: 'Vijay Sethupathi delivers a powerhouse performance in this critically acclaimed thriller.',
    country: 'India',
    region: 'Tamil Nadu',
    language: 'Tamil',
  },
  {
    id: 'msi008',
    title: 'The Family Man: Season 3',
    type: 'Web Series',
    platform: 'Amazon Prime Video',
    releaseMonth: 'November 2024',
    greybrainerScore: 8.8,
    posterUrl: 'https://via.placeholder.com/150x220/000080/FFFFFF?text=Family+Man+S3',
    summary: 'Manoj Bajpayee returns as Srikant Tiwari in this espionage thriller\'s much-awaited third season.',
    country: 'India',
    region: 'Maharashtra',
    language: 'Hindi',
  },
  {
    id: 'msi009',
    title: 'Aavesham',
    type: 'Movie',
    platform: 'Disney+ Hotstar',
    releaseMonth: 'April 2024',
    greybrainerScore: 8.7,
    posterUrl: 'https://via.placeholder.com/150x220/FF6347/FFFFFF?text=Aavesham',
    summary: 'Fahadh Faasil\'s charismatic performance drives this Malayalam action-comedy to critical acclaim.',
    country: 'India',
    region: 'Kerala',
    language: 'Malayalam',
  },
  {
    id: 'msi010',
    title: 'Heeramandi: The Diamond Bazaar',
    type: 'Web Series',
    platform: 'Netflix',
    releaseMonth: 'May 2024',
    greybrainerScore: 8.6,
    posterUrl: 'https://via.placeholder.com/150x220/800080/FFFFFF?text=Heeramandi',
    summary: 'Sanjay Leela Bhansali\'s opulent series explores the lives of courtesans in pre-independence India.',
    country: 'India',
    region: 'Rajasthan',
    language: 'Hindi',
  },
  {
    id: 'msi011',
    title: 'Bade Miyan Chote Miyan',
    type: 'Movie',
    platform: 'Netflix',
    releaseMonth: 'April 2024',
    greybrainerScore: 7.8,
    posterUrl: 'https://via.placeholder.com/150x220/FF1493/FFFFFF?text=BMCM+2024',
    summary: 'Akshay Kumar and Tiger Shroff team up in this action-packed entertainer with high-octane sequences.',
    country: 'India',
    region: 'Maharashtra',
    language: 'Hindi',
  },
  {
    id: 'msi012',
    title: 'Khel Khel Mein',
    type: 'Movie',
    platform: 'ZEE5',
    releaseMonth: 'August 2024',
    greybrainerScore: 7.9,
    posterUrl: 'https://via.placeholder.com/150x220/32CD32/FFFFFF?text=Khel+Khel+Mein',
    summary: 'Akshay Kumar leads this comedy-drama about friends whose secrets are revealed during a game.',
    country: 'India',
    region: 'Punjab',
    language: 'Hindi',
  },
  {
    id: 'msi013',
    title: 'Laapataa Ladies',
    type: 'Movie',
    platform: 'Netflix',
    releaseMonth: 'March 2024',
    greybrainerScore: 8.5,
    posterUrl: 'https://via.placeholder.com/150x220/FF69B4/FFFFFF?text=Laapataa+Ladies',
    summary: 'Kiran Rao\'s directorial comeback is a heartwarming tale of two brides who get swapped during a train journey.',
    country: 'India',
    region: 'Uttar Pradesh',
    language: 'Hindi',
  },
  {
    id: 'msi014',
    title: 'Premalu',
    type: 'Movie',
    platform: 'Disney+ Hotstar',
    releaseMonth: 'February 2024',
    greybrainerScore: 8.4,
    posterUrl: 'https://via.placeholder.com/150x220/20B2AA/FFFFFF?text=Premalu',
    summary: 'This Malayalam romantic comedy became a surprise hit with its relatable characters and fresh storytelling.',
    country: 'India',
    region: 'Kerala',
    language: 'Malayalam',
  },
  {
    id: 'msi015',
    title: 'Gunjan Saxena: The Kargil Girl',
    type: 'Movie',
    platform: 'Netflix',
    releaseMonth: 'August 2024',
    greybrainerScore: 8.3,
    posterUrl: 'https://via.placeholder.com/150x220/4169E1/FFFFFF?text=Gunjan+Saxena',
    summary: 'Janhvi Kapoor portrays India\'s first female combat pilot in this inspiring biographical drama.',
    country: 'India',
    region: 'Haryana',
    language: 'Hindi',
  },
  {
    id: 'msi016',
    title: 'Rocket Boys: Season 2',
    type: 'Web Series',
    platform: 'Sony LIV',
    releaseMonth: 'March 2024',
    greybrainerScore: 8.8,
    posterUrl: 'https://via.placeholder.com/150x220/B22222/FFFFFF?text=Rocket+Boys+S2',
    summary: 'The biographical series on Homi Bhabha and Vikram Sarabhai continues their scientific journey.',
    country: 'India',
    region: 'Maharashtra',
    language: 'Hindi',
  }
];
